spring.config.import=optional:file:.env[.properties]
spring.application.name=email-writer-sb

server.port=8080

groq.api.key=${GROQ_API_KEY:}
groq.api.url=${GROQ_API_URL:https://api.groq.com/openai/v1/chat/completions}
groq.model=${GROQ_MODEL:openai/gpt-oss-20b}

